name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@v1.5.2
        with:
          default: true
          ldproxy: true
      - name: copy config
        run: cp cfg.toml.example cfg.toml
      - name: Run cargo check
        run: cargo check --bins --example webserver
